import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

// Import Noto Sans font (supports ₹ and other Unicode characters)
import { NotoSansRegular } from './fonts/NotoSans-Regular-normal.js';
import { NotoSansBold } from './fonts/NotoSans-Bold-bold.js';

/**
 * Registers the Noto Sans font family (Regular + Bold) in a jsPDF document.
 * This enables proper rendering of Unicode characters like ₹, €, £, ¥, etc.
 */
function registerNotoSansFont(doc) {
  // Add Regular weight
  doc.addFileToVFS('NotoSans-Regular.ttf', NotoSansRegular);
  doc.addFont('NotoSans-Regular.ttf', 'NotoSans', 'normal');

  // Add Bold weight
  doc.addFileToVFS('NotoSans-Bold.ttf', NotoSansBold);
  doc.addFont('NotoSans-Bold.ttf', 'NotoSans', 'bold');

  // Set as default font
  doc.setFont('NotoSans', 'normal');
}

/**
 * Formats an amount with the user's currency symbol.
 * Falls back to '₹' if no currency symbol is provided.
 */
function formatAmount(amount, currencySymbol = '₹') {
  const formatted = (amount || 0).toLocaleString('en-IN');
  return `${currencySymbol}${formatted}`;
}

// ─── Brand Color Palette ───
const COLORS = {
  headerBg:      [26, 26, 46],      // #1A1A2E — deep navy
  headerAccent:  [79, 70, 229],     // indigo-600
  amber:         [245, 158, 11],    // amber-500
  white:         [255, 255, 255],
  textPrimary:   [30, 41, 59],      // slate-800
  textSecondary: [100, 116, 139],   // slate-500
  textMuted:     [148, 163, 184],   // slate-400
  rowEven:       [255, 255, 255],   // white
  rowOdd:        [248, 250, 252],   // slate-50
  danger:        [239, 68, 94],     // rose-500
  success:       [16, 185, 129],    // emerald-500
  totalBoxBg:    [248, 250, 252],   // slate-50
  totalBoxBorder:[226, 232, 240],   // slate-200
  divider:       [241, 245, 249],   // slate-100
};

/**
 * Draws the branded header panel on the current page.
 * Dark navy background with FinTrack branding.
 */
function drawBrandHeader(doc, pageWidth) {
  const headerHeight = 44;

  // Dark header background
  doc.setFillColor(...COLORS.headerBg);
  doc.rect(0, 0, pageWidth, headerHeight, 'F');

  // Accent stripe at the bottom of the header
  doc.setFillColor(...COLORS.headerAccent);
  doc.rect(0, headerHeight, pageWidth, 1.5, 'F');

  // Brand name
  doc.setFont('NotoSans', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(...COLORS.white);
  doc.text('FinTrack', 14, 18);

  // Tagline
  doc.setFont('NotoSans', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(...COLORS.amber);
  doc.text('Expense Manager Pro', 14, 25);

  // Report title — right aligned
  doc.setFont('NotoSans', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...COLORS.white);
  doc.text('EXPENSE REPORT', pageWidth - 14, 18, { align: 'right' });

  return headerHeight;
}

/**
 * Draws the footer on every page.
 */
function drawFooter(doc, pageWidth, pageHeight) {
  const footerY = pageHeight - 10;

  // Divider line
  doc.setDrawColor(...COLORS.divider);
  doc.setLineWidth(0.3);
  doc.line(14, footerY - 4, pageWidth - 14, footerY - 4);

  // Footer text
  doc.setFont('NotoSans', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.textMuted);
  doc.text('Generated by FinTrack — Expense Manager Pro', 14, footerY);
  doc.text(`Page ${doc.internal.getNumberOfPages()}`, pageWidth - 14, footerY, { align: 'right' });
}

/**
 * Exports expenses as a premium styled PDF report with proper Unicode font support.
 *
 * @param {Array} expenses - Array of expense objects
 * @param {Array} categories - Array of category objects
 * @param {Object|null} dateRange - Optional { from, to } date range strings
 * @param {Object} settings - Globals containing currency & dateFormat
 */
export function exportExpensesPDF(expenses, categories, dateRange = null, settings = {}) {
  const currencySymbol = settings.currency || '₹';
  const displayFormat = settings.dateFormat || 'dd/MM/yyyy';
  const fileStampFormat = 'yyyy-MM-dd';
  
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  const margin = 14;

  // Register custom Unicode font
  registerNotoSansFont(doc);

  // ─── Branded Header ───
  const headerHeight = drawBrandHeader(doc, pageWidth);

  // ─── Meta Information Row ───
  const metaY = headerHeight + 12;
  doc.setFont('NotoSans', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.textSecondary);

  if (dateRange) {
    doc.text(`Period: ${dateRange.from} — ${dateRange.to}`, margin, metaY);
  } else {
    doc.text(`Generated: ${format(new Date(), `${displayFormat}, hh:mm a`)}`, margin, metaY);
  }

  doc.text(`${expenses.length} transaction(s)`, pageWidth - margin, metaY, { align: 'right' });

  // Subtle divider below meta
  doc.setDrawColor(...COLORS.divider);
  doc.setLineWidth(0.3);
  doc.line(margin, metaY + 4, pageWidth - margin, metaY + 4);

  // ─── Table Data ───
  const tableData = expenses.map(exp => {
    const cat = categories.find(c => c.id === exp.category);
    return [
      exp.date ? format(new Date(exp.date), displayFormat) : '—',
      exp.title || '—',
      cat ? cat.name : exp.category || '—',
      formatAmount(exp.amount, currencySymbol),
      exp.note || '—',
    ];
  });

  // ─── Auto Table (Premium Styling) ───
  autoTable(doc, {
    startY: metaY + 10,
    head: [['DATE', 'TITLE', 'CATEGORY', 'AMOUNT', 'NOTE']],
    body: tableData,
    theme: 'grid',
    styles: {
      font: 'NotoSans',
      fontStyle: 'normal',
      fontSize: 8.5,
      cellPadding: { top: 5, right: 4, bottom: 5, left: 4 },
      lineColor: [226, 232, 240],
      lineWidth: 0.25,
      textColor: COLORS.textPrimary,
      valign: 'middle',
    },
    headStyles: {
      fillColor: COLORS.headerBg,
      textColor: COLORS.amber,
      fontSize: 8,
      fontStyle: 'bold',
      font: 'NotoSans',
      cellPadding: { top: 6, right: 4, bottom: 6, left: 4 },
      halign: 'left',
    },
    bodyStyles: {
      font: 'NotoSans',
    },
    alternateRowStyles: {
      fillColor: COLORS.rowOdd,
    },
    columnStyles: {
      0: { cellWidth: 26 },                                          // Date
      1: { cellWidth: 38 },                                          // Title
      2: { cellWidth: 36 },                                          // Category
      3: { cellWidth: 32, halign: 'right', fontStyle: 'bold' },      // Amount
      4: { cellWidth: 'auto', textColor: COLORS.textSecondary },     // Note
    },
    margin: { left: margin, right: margin },

    // Redraw brand header and footer on every new page
    didDrawPage: function(data) {
      // Footer on every page
      drawFooter(doc, pageWidth, pageHeight);

      // Brand header on continuation pages (page > 1)
      if (data.pageNumber > 1) {
        drawBrandHeader(doc, pageWidth);
      }
    },
  });

  // ─── Total Summary Box ───
  const total = expenses.reduce((sum, e) => sum + (e.amount || 0), 0);
  const finalY = doc.lastAutoTable.finalY + 10;
  const boxWidth = 182;
  const boxHeight = 26;

  // Box background with rounded corners
  doc.setFillColor(...COLORS.totalBoxBg);
  doc.setDrawColor(...COLORS.headerAccent);
  doc.setLineWidth(0.6);
  doc.roundedRect(margin, finalY, boxWidth, boxHeight, 3, 3, 'FD');

  // "TOTAL EXPENDITURE" label
  doc.setFont('NotoSans', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.textSecondary);
  doc.text('TOTAL EXPENDITURE', margin + 8, finalY + 10);

  // Amount — large and bold
  doc.setFont('NotoSans', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.danger);
  doc.text(formatAmount(total, currencySymbol), margin + 8, finalY + 20);

  // Transaction count — right side
  doc.setFont('NotoSans', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.textMuted);
  doc.text(`${expenses.length} transaction(s)`, pageWidth - margin - 8, finalY + 16, { align: 'right' });

  // ─── Footer on first page (handled by didDrawPage for table pages, but ensure it's on the last page too) ───
  drawFooter(doc, pageWidth, pageHeight);

  doc.save(`expense-report-${format(new Date(), fileStampFormat)}.pdf`);
}
