import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

// Import Noto Sans font (supports ₹ and other Unicode characters)
import { NotoSansRegular } from './fonts/NotoSans-Regular-normal.js';
import { NotoSansBold } from './fonts/NotoSans-Bold-bold.js';

/**
 * Registers the Noto Sans font family (Regular + Bold) in a jsPDF document.
 * This enables proper rendering of Unicode characters like ₹, €, £, ¥, etc.
 */
function registerNotoSansFont(doc) {
  // Add Regular weight
  doc.addFileToVFS('NotoSans-Regular.ttf', NotoSansRegular);
  doc.addFont('NotoSans-Regular.ttf', 'NotoSans', 'normal');

  // Add Bold weight
  doc.addFileToVFS('NotoSans-Bold.ttf', NotoSansBold);
  doc.addFont('NotoSans-Bold.ttf', 'NotoSans', 'bold');

  // Set as default font
  doc.setFont('NotoSans', 'normal');
}

/**
 * Formats an amount with the user's currency symbol.
 * Falls back to '₹' if no currency symbol is provided.
 */
function formatAmount(amount, currencySymbol = '₹') {
  const formatted = (amount || 0).toLocaleString('en-IN');
  return `${currencySymbol}${formatted}`;
}

/**
 * Exports expenses as a styled PDF report with proper Unicode font support.
 *
 * @param {Array} expenses - Array of expense objects
 * @param {Array} categories - Array of category objects
 * @param {Object|null} dateRange - Optional { from, to } date range strings
 * @param {Object} settings - Globals containing currency & dateFormat
 */
export function exportExpensesPDF(expenses, categories, dateRange = null, settings = {}) {
  const currencySymbol = settings.currency || '₹';
  const displayFormat = settings.dateFormat || 'dd/MM/yyyy';
  const fileStampFormat = 'yyyy-MM-dd';
  
  const doc = new jsPDF();

  // Register custom Unicode font
  registerNotoSansFont(doc);

  // ─── Header ───
  doc.setFont('NotoSans', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(79, 70, 229); // primary-600
  doc.text('FinTrack', 14, 22);

  doc.setFont('NotoSans', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text('Expense Manager Pro', 14, 28);

  // ─── Title ───
  doc.setFont('NotoSans', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(30, 41, 59); // slate-800
  doc.text('Expense Report', 14, 42);

  // ─── Date range / Generated date ───
  doc.setFont('NotoSans', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  if (dateRange) {
    doc.text(`Period: ${dateRange.from} — ${dateRange.to}`, 14, 49);
  } else {
    doc.text(`Generated: ${format(new Date(), `${displayFormat}, hh:mm a`)}`, 14, 49);
  }

  // ─── Table Data ───
  const tableData = expenses.map(exp => {
    const cat = categories.find(c => c.id === exp.category);
    return [
      exp.date ? format(new Date(exp.date), displayFormat) : '—',
      exp.title || '—',
      cat ? cat.name : exp.category || '—',
      formatAmount(exp.amount, currencySymbol),
      exp.note || '—',
    ];
  });

  // ─── Auto Table ───
  autoTable(doc, {
    startY: 56,
    head: [['Date', 'Title', 'Category', 'Amount', 'Note']],
    body: tableData,
    styles: {
      font: 'NotoSans',
      fontStyle: 'normal',
      fontSize: 8.5,
      cellPadding: 4,
    },
    headStyles: {
      fillColor: [79, 70, 229],
      textColor: 255,
      fontSize: 9,
      fontStyle: 'bold',
      font: 'NotoSans',
    },
    bodyStyles: {
      textColor: [51, 65, 85],
      font: 'NotoSans',
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    columnStyles: {
      0: { cellWidth: 28 },                             // Date
      1: { cellWidth: 32 },                             // Title
      2: { cellWidth: 38 },                             // Category
      3: { cellWidth: 36, halign: 'right', fontStyle: 'bold' }, // Amount — wider for currency + number
      4: { cellWidth: 'auto' },                          // Note
    },
    margin: { left: 14, right: 14 },
  });

  // ─── Total ───
  const total = expenses.reduce((sum, e) => sum + (e.amount || 0), 0);
  const finalY = doc.lastAutoTable.finalY + 12;

  doc.setFont('NotoSans', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text(`Total: ${formatAmount(total, currencySymbol)}`, 14, finalY);

  doc.setFont('NotoSans', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(`${expenses.length} transaction(s)`, 14, finalY + 6);

  // ─── Footer ───
  const pageHeight = doc.internal.pageSize.height;
  doc.setFont('NotoSans', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by FinTrack — Expense Manager Pro', 14, pageHeight - 10);

  doc.save(`expense-report-${format(new Date(), fileStampFormat)}.pdf`);
}
